//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoanWindow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCao
    {
        public string IDBaoCao { get; set; }
        public string IDDeTai { get; set; }
        public Nullable<int> LanBaoCao { get; set; }
        public string TaiLieu { get; set; }
        public string NhanXet { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual DeTai DeTai { get; set; }
    }
}
