//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoanWindow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public string ID { get; set; }
        public string HoiDong { get; set; }
        public Nullable<int> Diem1 { get; set; }
    
        public virtual HoiDong HoiDong1 { get; set; }
    }
}
